version: '3.5'

services:

  concentrator:
    build:
      context: .
      dockerfile: ./concentrator/Dockerfile
    container_name: concentrator
    networks:
      network_usine:
          ipv4_address: 172.28.1.3

  unit1:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    container_name: unit1

  unit2:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    container_name: unit2

  unit3:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    container_name: unit3

  unit4:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    container_name: unit4

  unit5:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    container_name: unit5

networks:
  network_usine:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
