version: '3.5'

services:

  unit1:
    build:
      context: .
      dockerfile: ./units/unit1/Dockerfile
    container_name: unit1

  unit2:
    build:
      context: .
      dockerfile: ./units/unit2/Dockerfile
    container_name: unit2

  unit3:
    build:
      context: .
      dockerfile: ./units/unit3/Dockerfile
    container_name: unit3

  unit4:
    build:
      context: .
      dockerfile: ./units/unit4/Dockerfile
    container_name: unit4

  unit5:
    build:
      context: .
      dockerfile: ./units/unit5/Dockerfile
    container_name: unit5

  concentrator:
    build:
      context: .
      dockerfile: ./concentrator/Dockerfile
    container_name: concentrator
