version: '3.5'

services:

  concentrator:
    build:
      context: .
      dockerfile: ./concentrator/Dockerfile
    container_name: concentrator
    networks:
      network_usine:
          ipv4_address: 172.28.1.3

  unit1:
    build:
      context: .
      dockerfile: ./units/unit1/Dockerfile
    container_name: unit1
    networks:
      - network_usine
    depends_on:
      - concentrator

  unit2:
    build:
      context: .
      dockerfile: ./units/unit2/Dockerfile
    container_name: unit2
    networks:
      - network_usine
    depends_on:
      - concentrator

  unit3:
    build:
      context: .
      dockerfile: ./units/unit3/Dockerfile
    container_name: unit3
    networks:
      - network_usine
    depends_on:
      - concentrator

  unit4:
    build:
      context: .
      dockerfile: ./units/unit4/Dockerfile
    container_name: unit4
    networks:
      - network_usine
    depends_on:
      - concentrator

  unit5:
    build:
      context: .
      dockerfile: ./units/unit5/Dockerfile
    container_name: unit5
    networks:
      - network_usine
    depends_on:
      - concentrator

networks:
  network_usine:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
